<?php

namespace flowcode\smooth\mvc;

use flowcode\smooth\mvc\HttpRequest;

require_once dirname(__FILE__) . '/../../../../../src/flowcode/smooth/mvc/HttpRequest.class.php';

/**
 * Test class for HttpRequest.
 * Generated by PHPUnit on 2012-10-13 at 03:24:53.
 */
class HttpRequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HttpRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getControllerClass
     * @todo Implement testGetControllerClass().
     */
    public function testGetControllerClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getControllerName
     * @todo Implement testGetControllerName().
     */
    public function testGetControllerName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getAction
     * @todo Implement testGetAction().
     */
    public function testGetAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::setControllerName
     * @todo Implement testSetControllerName().
     */
    public function testSetControllerName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::setAction
     * @todo Implement testSetAction().
     */
    public function testSetAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getParams
     * @todo Implement testGetParams().
     */
    public function testGetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getParameter
     * @todo Implement testGetParameter().
     */
    public function testGetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\mvc\kernel\HttpRequest::getRequestedUrl
     * @todo Implement testGetRequestedUrl().
     */
    public function testGetRequestedUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
