<?php

namespace flowcode\smooth\mvc;

require_once dirname(__FILE__) . '/../../../../../src/flowcode/smooth/mvc/HttpRequestBuilder.class.php';

/**
 * Test class for HttpRequestBuilder.
 * Generated by PHPUnit on 2012-10-14 at 17:35:21.
 */
class HttpRequestBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpRequestBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HttpRequestBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\smooth\mvc\HttpRequestBuilder::buildFromRequestUrl
     * @todo Implement testBuildFromRequestUrl().
     */
    public function testBuildFromRequestUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
