<?php

use flowcode\wing\mvc\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-06 at 20:44:38.
 */
class KernelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Kernel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Kernel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::handleRequest
     * @todo   Implement testHandleRequest().
     */
    public function testHandleRequest() {

        $requestedUrl = "home/index";
        $this->object->handleRequest($requestedUrl);
    }

}
